### ISSUE TITLE
[BUG] Unexpected uniform thickness calculated by MembThickness 

### ISSUE THREAD

**Issue by dnusha1994** [p-j-smith/lipyphilic#100]
**Describe the bug**
I am trying to plot a 2D membrane thickness map, using the instructions found in the API documentation. I assign my leaflets, and I have verified that this all works ok, and when I calculate the global membrane thickness it gives a plausible value. However when I use the return_surface keyword to give local membrane thicknesses, the code just appears to copy the global value and replicate it at all grid points i.e. I don't get the local data. This occurs with and without interpolation. 

**To Reproduce**
u = mda.Universe("step7_production.tpr", "step7_production.part0002.xtc")

leaflets = AssignLeaflets(
  universe=u,
  lipid_sel="name PO1 PO2 PO4",n_bins=50 # assuming we are using the MARTINI forcefield
)
leaflets.run(verbose=True,start=9800,stop=9801)

memb_thickness = MembThickness(
  universe=u,
  leaflets=leaflets.filter_leaflets("resname RAMP POPE POPG"),  
  lipid_sel="(resname RAMP POPE POPG and name PO1 PO2 PO4)",n_bins=50,return_surface=True,interpolate=True
)

memb_thickness.run(
  start=9800,
  stop=9801,
  step=None,
  verbose=True
)

```

**Expected behaviour**
I get a 2D membrane thickness map with differing values at each grid point
**Actual behaviour**
A 2D membrane thickness map with exact the same value at each point (the global membrane thickness)

[[[40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]
  [40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]
  [40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]
  ...
  [40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]
  [40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]
  [40.11803949 40.11803949 40.11803949 ... 40.11803949 40.11803949
   40.11803949]]]
**Additional context**

- Which version of lipyphilic are you using?
0.0.10
- Which version of Python are you using?
3.9.12
- Which OS are you using?
Ubuntu

**Comment by p-j-smith** [comment]
Hi @dnusha1994 sorry for not getting back to you sooner. Did you have any luck figuring out what was happening? If not, would you be able to share a small part of your trajectory (even just the frame you're analysing here) and I'll take a look at it

**Comment by dnusha1994** [comment]
Apologies for not responding - I didn't use this analysis in the end. However I wanted to use it in another project, so went back and had a look at the source code for the MembThickness class. I believe the reason this is occurring may be due to the line in the source code:

if self.n_bins > 1:
     thickness=np.mean(upper_surface-lower_surface)

If I am not mistaken, shouldn't this be something like:
thickness=np.mean([upper_surface - lower_surface],axis=0)

I am not a very experienced coder though, so I may have misunderstood.

Best wishes,
Dhanushka

**Comment by p-j-smith** [comment]
> Should the thickness grid not be [upper_surface-lower_surface], as opposed to the thickness value calculated in previous lines? Let me know if I have misunderstood this.

Yep, you're right, thanks so much for looking into it and figuring out what the issue is!
