### ISSUE TITLE
`AssignLeaflets` fails when `xy` dimensions are not equal

### ISSUE THREAD

**Issue by p-j-smith** [p-j-smith/lipyphilic#132]
Hi @p-j-smith and @pablo-arantes, I had encountered the same IndexError a while ago (still in version 0.9.0, but as far as I can tell this part is unchanged in 0.10.0). The problem appeared always when having different x and y dimensions, i.e., AssignLeaflets works fine on square membranes, and fails otherwise. 

At least in my case, the problem is not caused by missing z positions in `self.membrane.positions`. In my test case the y dimension is roughly twice as long as the x dimension. Then the IndexError is caused by `lipid_y_bins` having some bin indices = 2 and `memb_midpoint_xy.shape` being `(2,2)`. Apparently, the incorrect bin indices are caused by usage of the same bins for x and y in `scipy.stats.binned_statistic_2d`. 

The problem is solved by 
```
        x_bins = memb_midpoint_xy.x_edge
        y_bins = memb_midpoint_xy.y_edge
     
        # get the binnumbers for each lipid
        lipid_x_bins, lipid_y_bins = scipy.stats.binned_statistic_2d(
            x=self.membrane.positions[:, 0],
            y=self.membrane.positions[:, 1],
            values=self.membrane.positions[:, 2],
            statistic="mean",
            bins=(x_bins, y_bins),
            expand_binnumbers=True
        ).binnumber -1  # These were bin numbers, now bin indices  # noqa: E225
```

and similar changes in the other calls to `scipy.stats.binned_statistic_2d`

_Originally posted by @kaistroh in https://github.com/p-j-smith/lipyphilic/issues/101#issuecomment-1801375567_

**Comment by CharlyEmpereurmot** [comment]
Hi @p-j-smith,
I'm having an error that is likely related to `xy` dimensions being unequal, using routine `lipyphilic.lib.z_positions.Zpositions`:

```
Traceback (most recent call last):
  File "stuff/analysis_enrichment.py", line 170, in <module>
    z_positions.run()
  File "/home/charly/anaconda3/lib/python3.8/site-packages/lipyphilic/lib/base.py", line 194, in run
    self._single_frame()
  File "/home/charly/anaconda3/lib/python3.8/site-packages/lipyphilic/lib/z_positions.py", line 240, in _single_frame
    species_zpos = species_atoms.positions[:, 2] - memb_midpoint_xy.statistic[species_x_bins, species_y_bins]
IndexError: index 5 is out of bounds for axis 1 with size 5
```

Cheers for the cool package!

**Comment by p-j-smith** [comment]
Hi @CharlyEmpereurmot thanks for reporting the issue - I think it should be fixed in the [next release](https://github.com/p-j-smith/lipyphilic/releases/tag/v0.11.0), which is [being created now](https://github.com/p-j-smith/lipyphilic/actions/runs/7045067165), which should be available on PyPI shortly (but it usually takes a couple of days before it's available through Conda).

Just to let you know, in this new release I've changed the API a fair bit. Instead of:

```python
from lipyphilic.lib.z_positions import ZPositions
z_positions = ZPositions(...)
```
I would recommend:
```python
import lipyphilic as lpp
z_positions = lpp.analysis.ZPositions(...)
```

For now, the previous approach should still work but issue a deprecaion warning. Let me know if you still have any issues!
