### ISSUE TITLE
the error of "from lipyphilic.lib.z_positions import ZThickness"

### ISSUE THREAD

**Issue by yang-guoli** [p-j-smith/lipyphilic#82]
**What is the topic of your question**: Installation / Usage / Documentation / Other
Please indicate the topic in the title of your question
the error of "from lipyphilic.lib.z_positions import ZThickness"
**Add your question below**:
i was use the conda install lipyphilic and succeed, but when i use the lipyphilic report the follow error:
 
![image](https://user-images.githubusercontent.com/73353085/147470453-4d627328-bc48-41d5-a204-a7fca7b1b1d7.png)

can you help me to tackle this problem?

**Comment by p-j-smith** [comment]
Hi @yang-guoli, I think you are running a different Python interpreter to the one lipyphilic was installed for. I have a few questions for you:

* How did you install lipyphilic with conda - did you use a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) or did you type `conda install -c conda-forge lipyphilic` into the terminal without creating/activating an environment?
* Please could you type `which python` in the terminal to check what Python interpreter you are using
* Please could you type `conda list` in the terminal and check that both `lipyphilic` and `python` are in the list that's printed, and check that the Python version is the same 

If you are using the default Python interpreter (something like `/usr/local/bin/python`), this will not be able to find the conda packages you have installed. Instead, you will need to use anaconda's Python interpreter. To do this you will need to type `conda activate` before running your script.

**Comment by yang-guoli** [comment]
> Thanks for your reply, i will answer your question as follows:

1.      I installed the lipyphlic by used the conda env that was activated.
2.      I use the "conda list " command to inspect the lipyphilic package, and the package in the list.
![image](https://user-images.githubusercontent.com/73353085/147619682-b7ea7b43-d6bc-4652-9888-914f8d259f7d.png)

but when i run the script, the error still exist
![image](https://user-images.githubusercontent.com/73353085/147619803-26c78268-64c9-4b2e-9e07-c6fb44cb5fea.png)

**Comment by p-j-smith** [comment]
Ah, I think I know what the issue is now - the problem is that you have called your script `lipyphilic.py`. If you run Python from the directory containing `lipyphilic.py`, Python will treat this script like a module. So when you try to `import lipyphilic` Python will attempt to import your script `lipyphilic.py` rather than the package you have installed. It should run okay for you if you rename your script to something like `thickness.py` or `lipyphilic-thickness.py`.

**Comment by yang-guoli** [comment]
@p-j-smith 
Ok, that's is working, and thanks for your help.

**Comment by p-j-smith** [comment]
That's great, happy to hear it's working for you now
