### ISSUE TITLE
[QUESTION] error aboubt "Calculate 2D PMFs from joint probability distributions"

### ISSUE THREAD

**Issue by yang-guoli** [p-j-smith/lipyphilic#99]
**What is the topic of your question**: Installation / Usage / Documentation / Other
Please indicate the topic in the title of your question

**Add your question below**:
After I learned to use a script to compute two-dimensional PMFS from joint probability distributions, I got an error: ValueError: 'ob1' and 'ob2' must be arrays of the same shape.  but the length of ob1 equal to length of ob2:
![image](https://user-images.githubusercontent.com/73353085/192922513-b9566c01-031c-4b14-acc8-f4d4d003bdbd.png)
can you help me ?

**Comment by p-j-smith** [comment]
Hi @yang-guoli , I'm sorry for the super slow reply and imagine you solved your issue, but I'll reply here in case anyone else runs into a similar issue. Based on your example, I'm guessing that you have run the two analyses over a different set of frames.

`JointDensity` requires that the two input arrays have the same *shape* - meaning they have both the same number of  *rows* (lipids) and the same number of *columns* (timesteps). You've checked the length of your arrays are the same, but this only checks the number of rows. If you print `angles.z_angles.shape` and `height.z_positions.shape` you will probably see they have a different number of columns.

Sorry again for the massive delay in getting back to you!
